/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as appARouteImport } from './routes/(app)/a'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'
import { Route as appASearchRouteImport } from './routes/(app)/a.search'
import { Route as appAHomeRouteImport } from './routes/(app)/a.home'
import { Route as appAArmeRouteImport } from './routes/(app)/a.arme'
import { Route as appAForumIndexRouteImport } from './routes/(app)/a.forum.index'
import { Route as appAUlasanUlasanIdRouteImport } from './routes/(app)/a.ulasan.$ulasanId'
import { Route as appAForumForumIdRouteImport } from './routes/(app)/a.forum.$forumId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const appARoute = appARouteImport.update({
  id: '/(app)/a',
  path: '/a',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const appASearchRoute = appASearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => appARoute,
} as any)
const appAHomeRoute = appAHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => appARoute,
} as any)
const appAArmeRoute = appAArmeRouteImport.update({
  id: '/arme',
  path: '/arme',
  getParentRoute: () => appARoute,
} as any)
const appAForumIndexRoute = appAForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => appARoute,
} as any)
const appAUlasanUlasanIdRoute = appAUlasanUlasanIdRouteImport.update({
  id: '/ulasan/$ulasanId',
  path: '/ulasan/$ulasanId',
  getParentRoute: () => appARoute,
} as any)
const appAForumForumIdRoute = appAForumForumIdRouteImport.update({
  id: '/forum/$forumId',
  path: '/forum/$forumId',
  getParentRoute: () => appARoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a': typeof appARouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/a/arme': typeof appAArmeRoute
  '/a/home': typeof appAHomeRoute
  '/a/search': typeof appASearchRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/a/forum/$forumId': typeof appAForumForumIdRoute
  '/a/ulasan/$ulasanId': typeof appAUlasanUlasanIdRoute
  '/a/forum': typeof appAForumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a': typeof appARouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/a/arme': typeof appAArmeRoute
  '/a/home': typeof appAHomeRoute
  '/a/search': typeof appASearchRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/a/forum/$forumId': typeof appAForumForumIdRoute
  '/a/ulasan/$ulasanId': typeof appAUlasanUlasanIdRoute
  '/a/forum': typeof appAForumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/a': typeof appARouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/(app)/a/arme': typeof appAArmeRoute
  '/(app)/a/home': typeof appAHomeRoute
  '/(app)/a/search': typeof appASearchRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/(app)/a/forum/$forumId': typeof appAForumForumIdRoute
  '/(app)/a/ulasan/$ulasanId': typeof appAUlasanUlasanIdRoute
  '/(app)/a/forum/': typeof appAForumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a'
    | '/api/chat'
    | '/a/arme'
    | '/a/home'
    | '/a/search'
    | '/auth/google/callback'
    | '/a/forum/$forumId'
    | '/a/ulasan/$ulasanId'
    | '/a/forum'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a'
    | '/api/chat'
    | '/a/arme'
    | '/a/home'
    | '/a/search'
    | '/auth/google/callback'
    | '/a/forum/$forumId'
    | '/a/ulasan/$ulasanId'
    | '/a/forum'
  id:
    | '__root__'
    | '/'
    | '/(app)/a'
    | '/api/chat'
    | '/(app)/a/arme'
    | '/(app)/a/home'
    | '/(app)/a/search'
    | '/auth/google/callback'
    | '/(app)/a/forum/$forumId'
    | '/(app)/a/ulasan/$ulasanId'
    | '/(app)/a/forum/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appARoute: typeof appARouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/a': {
      id: '/(app)/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof appARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/a/search': {
      id: '/(app)/a/search'
      path: '/search'
      fullPath: '/a/search'
      preLoaderRoute: typeof appASearchRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/home': {
      id: '/(app)/a/home'
      path: '/home'
      fullPath: '/a/home'
      preLoaderRoute: typeof appAHomeRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/arme': {
      id: '/(app)/a/arme'
      path: '/arme'
      fullPath: '/a/arme'
      preLoaderRoute: typeof appAArmeRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/forum/': {
      id: '/(app)/a/forum/'
      path: '/forum'
      fullPath: '/a/forum'
      preLoaderRoute: typeof appAForumIndexRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/ulasan/$ulasanId': {
      id: '/(app)/a/ulasan/$ulasanId'
      path: '/ulasan/$ulasanId'
      fullPath: '/a/ulasan/$ulasanId'
      preLoaderRoute: typeof appAUlasanUlasanIdRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/forum/$forumId': {
      id: '/(app)/a/forum/$forumId'
      path: '/forum/$forumId'
      fullPath: '/a/forum/$forumId'
      preLoaderRoute: typeof appAForumForumIdRouteImport
      parentRoute: typeof appARoute
    }
  }
}

interface appARouteChildren {
  appAArmeRoute: typeof appAArmeRoute
  appAHomeRoute: typeof appAHomeRoute
  appASearchRoute: typeof appASearchRoute
  appAForumForumIdRoute: typeof appAForumForumIdRoute
  appAUlasanUlasanIdRoute: typeof appAUlasanUlasanIdRoute
  appAForumIndexRoute: typeof appAForumIndexRoute
}

const appARouteChildren: appARouteChildren = {
  appAArmeRoute: appAArmeRoute,
  appAHomeRoute: appAHomeRoute,
  appASearchRoute: appASearchRoute,
  appAForumForumIdRoute: appAForumForumIdRoute,
  appAUlasanUlasanIdRoute: appAUlasanUlasanIdRoute,
  appAForumIndexRoute: appAForumIndexRoute,
}

const appARouteWithChildren = appARoute._addFileChildren(appARouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appARoute: appARouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
