/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as appARouteImport } from './routes/(app)/a'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'
import { Route as ApiChatMessagesRouteImport } from './routes/api/chat.messages'
import { Route as ApiChatHistoryRouteImport } from './routes/api/chat.history'
import { Route as appASearchRouteImport } from './routes/(app)/a.search'
import { Route as appAProfileRouteImport } from './routes/(app)/a.profile'
import { Route as appAHomeRouteImport } from './routes/(app)/a.home'
import { Route as appAArmeRouteImport } from './routes/(app)/a.arme'
import { Route as appAAdminRouteImport } from './routes/(app)/a.admin'
import { Route as appAForumIndexRouteImport } from './routes/(app)/a.forum.index'
import { Route as appAUlasanUlasanIdRouteImport } from './routes/(app)/a.ulasan.$ulasanId'
import { Route as appAUUserIdRouteImport } from './routes/(app)/a.u.$userId'
import { Route as appAForumForumIdRouteImport } from './routes/(app)/a.forum.$forumId'
import { Route as appAAdminSubjectsRouteImport } from './routes/(app)/a.admin.subjects'
import { Route as appAAdminLecturersRouteImport } from './routes/(app)/a.admin.lecturers'
import { Route as appAAdminDashboardRouteImport } from './routes/(app)/a.admin.dashboard'
import { Route as appAAdminContentRouteImport } from './routes/(app)/a.admin.content'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const appARoute = appARouteImport.update({
  id: '/(app)/a',
  path: '/a',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatMessagesRoute = ApiChatMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatHistoryRoute = ApiChatHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ApiChatRoute,
} as any)
const appASearchRoute = appASearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => appARoute,
} as any)
const appAProfileRoute = appAProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appARoute,
} as any)
const appAHomeRoute = appAHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => appARoute,
} as any)
const appAArmeRoute = appAArmeRouteImport.update({
  id: '/arme',
  path: '/arme',
  getParentRoute: () => appARoute,
} as any)
const appAAdminRoute = appAAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => appARoute,
} as any)
const appAForumIndexRoute = appAForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => appARoute,
} as any)
const appAUlasanUlasanIdRoute = appAUlasanUlasanIdRouteImport.update({
  id: '/ulasan/$ulasanId',
  path: '/ulasan/$ulasanId',
  getParentRoute: () => appARoute,
} as any)
const appAUUserIdRoute = appAUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => appARoute,
} as any)
const appAForumForumIdRoute = appAForumForumIdRouteImport.update({
  id: '/forum/$forumId',
  path: '/forum/$forumId',
  getParentRoute: () => appARoute,
} as any)
const appAAdminSubjectsRoute = appAAdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => appAAdminRoute,
} as any)
const appAAdminLecturersRoute = appAAdminLecturersRouteImport.update({
  id: '/lecturers',
  path: '/lecturers',
  getParentRoute: () => appAAdminRoute,
} as any)
const appAAdminDashboardRoute = appAAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appAAdminRoute,
} as any)
const appAAdminContentRoute = appAAdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => appAAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a': typeof appARouteWithChildren
  '/api/chat': typeof ApiChatRouteWithChildren
  '/a/admin': typeof appAAdminRouteWithChildren
  '/a/arme': typeof appAArmeRoute
  '/a/home': typeof appAHomeRoute
  '/a/profile': typeof appAProfileRoute
  '/a/search': typeof appASearchRoute
  '/api/chat/history': typeof ApiChatHistoryRoute
  '/api/chat/messages': typeof ApiChatMessagesRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/a/admin/content': typeof appAAdminContentRoute
  '/a/admin/dashboard': typeof appAAdminDashboardRoute
  '/a/admin/lecturers': typeof appAAdminLecturersRoute
  '/a/admin/subjects': typeof appAAdminSubjectsRoute
  '/a/forum/$forumId': typeof appAForumForumIdRoute
  '/a/u/$userId': typeof appAUUserIdRoute
  '/a/ulasan/$ulasanId': typeof appAUlasanUlasanIdRoute
  '/a/forum': typeof appAForumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a': typeof appARouteWithChildren
  '/api/chat': typeof ApiChatRouteWithChildren
  '/a/admin': typeof appAAdminRouteWithChildren
  '/a/arme': typeof appAArmeRoute
  '/a/home': typeof appAHomeRoute
  '/a/profile': typeof appAProfileRoute
  '/a/search': typeof appASearchRoute
  '/api/chat/history': typeof ApiChatHistoryRoute
  '/api/chat/messages': typeof ApiChatMessagesRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/a/admin/content': typeof appAAdminContentRoute
  '/a/admin/dashboard': typeof appAAdminDashboardRoute
  '/a/admin/lecturers': typeof appAAdminLecturersRoute
  '/a/admin/subjects': typeof appAAdminSubjectsRoute
  '/a/forum/$forumId': typeof appAForumForumIdRoute
  '/a/u/$userId': typeof appAUUserIdRoute
  '/a/ulasan/$ulasanId': typeof appAUlasanUlasanIdRoute
  '/a/forum': typeof appAForumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/a': typeof appARouteWithChildren
  '/api/chat': typeof ApiChatRouteWithChildren
  '/(app)/a/admin': typeof appAAdminRouteWithChildren
  '/(app)/a/arme': typeof appAArmeRoute
  '/(app)/a/home': typeof appAHomeRoute
  '/(app)/a/profile': typeof appAProfileRoute
  '/(app)/a/search': typeof appASearchRoute
  '/api/chat/history': typeof ApiChatHistoryRoute
  '/api/chat/messages': typeof ApiChatMessagesRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/(app)/a/admin/content': typeof appAAdminContentRoute
  '/(app)/a/admin/dashboard': typeof appAAdminDashboardRoute
  '/(app)/a/admin/lecturers': typeof appAAdminLecturersRoute
  '/(app)/a/admin/subjects': typeof appAAdminSubjectsRoute
  '/(app)/a/forum/$forumId': typeof appAForumForumIdRoute
  '/(app)/a/u/$userId': typeof appAUUserIdRoute
  '/(app)/a/ulasan/$ulasanId': typeof appAUlasanUlasanIdRoute
  '/(app)/a/forum/': typeof appAForumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a'
    | '/api/chat'
    | '/a/admin'
    | '/a/arme'
    | '/a/home'
    | '/a/profile'
    | '/a/search'
    | '/api/chat/history'
    | '/api/chat/messages'
    | '/auth/google/callback'
    | '/a/admin/content'
    | '/a/admin/dashboard'
    | '/a/admin/lecturers'
    | '/a/admin/subjects'
    | '/a/forum/$forumId'
    | '/a/u/$userId'
    | '/a/ulasan/$ulasanId'
    | '/a/forum'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a'
    | '/api/chat'
    | '/a/admin'
    | '/a/arme'
    | '/a/home'
    | '/a/profile'
    | '/a/search'
    | '/api/chat/history'
    | '/api/chat/messages'
    | '/auth/google/callback'
    | '/a/admin/content'
    | '/a/admin/dashboard'
    | '/a/admin/lecturers'
    | '/a/admin/subjects'
    | '/a/forum/$forumId'
    | '/a/u/$userId'
    | '/a/ulasan/$ulasanId'
    | '/a/forum'
  id:
    | '__root__'
    | '/'
    | '/(app)/a'
    | '/api/chat'
    | '/(app)/a/admin'
    | '/(app)/a/arme'
    | '/(app)/a/home'
    | '/(app)/a/profile'
    | '/(app)/a/search'
    | '/api/chat/history'
    | '/api/chat/messages'
    | '/auth/google/callback'
    | '/(app)/a/admin/content'
    | '/(app)/a/admin/dashboard'
    | '/(app)/a/admin/lecturers'
    | '/(app)/a/admin/subjects'
    | '/(app)/a/forum/$forumId'
    | '/(app)/a/u/$userId'
    | '/(app)/a/ulasan/$ulasanId'
    | '/(app)/a/forum/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appARoute: typeof appARouteWithChildren
  ApiChatRoute: typeof ApiChatRouteWithChildren
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/a': {
      id: '/(app)/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof appARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/messages': {
      id: '/api/chat/messages'
      path: '/messages'
      fullPath: '/api/chat/messages'
      preLoaderRoute: typeof ApiChatMessagesRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/history': {
      id: '/api/chat/history'
      path: '/history'
      fullPath: '/api/chat/history'
      preLoaderRoute: typeof ApiChatHistoryRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/(app)/a/search': {
      id: '/(app)/a/search'
      path: '/search'
      fullPath: '/a/search'
      preLoaderRoute: typeof appASearchRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/profile': {
      id: '/(app)/a/profile'
      path: '/profile'
      fullPath: '/a/profile'
      preLoaderRoute: typeof appAProfileRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/home': {
      id: '/(app)/a/home'
      path: '/home'
      fullPath: '/a/home'
      preLoaderRoute: typeof appAHomeRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/arme': {
      id: '/(app)/a/arme'
      path: '/arme'
      fullPath: '/a/arme'
      preLoaderRoute: typeof appAArmeRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/admin': {
      id: '/(app)/a/admin'
      path: '/admin'
      fullPath: '/a/admin'
      preLoaderRoute: typeof appAAdminRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/forum/': {
      id: '/(app)/a/forum/'
      path: '/forum'
      fullPath: '/a/forum'
      preLoaderRoute: typeof appAForumIndexRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/ulasan/$ulasanId': {
      id: '/(app)/a/ulasan/$ulasanId'
      path: '/ulasan/$ulasanId'
      fullPath: '/a/ulasan/$ulasanId'
      preLoaderRoute: typeof appAUlasanUlasanIdRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/u/$userId': {
      id: '/(app)/a/u/$userId'
      path: '/u/$userId'
      fullPath: '/a/u/$userId'
      preLoaderRoute: typeof appAUUserIdRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/forum/$forumId': {
      id: '/(app)/a/forum/$forumId'
      path: '/forum/$forumId'
      fullPath: '/a/forum/$forumId'
      preLoaderRoute: typeof appAForumForumIdRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/admin/subjects': {
      id: '/(app)/a/admin/subjects'
      path: '/subjects'
      fullPath: '/a/admin/subjects'
      preLoaderRoute: typeof appAAdminSubjectsRouteImport
      parentRoute: typeof appAAdminRoute
    }
    '/(app)/a/admin/lecturers': {
      id: '/(app)/a/admin/lecturers'
      path: '/lecturers'
      fullPath: '/a/admin/lecturers'
      preLoaderRoute: typeof appAAdminLecturersRouteImport
      parentRoute: typeof appAAdminRoute
    }
    '/(app)/a/admin/dashboard': {
      id: '/(app)/a/admin/dashboard'
      path: '/dashboard'
      fullPath: '/a/admin/dashboard'
      preLoaderRoute: typeof appAAdminDashboardRouteImport
      parentRoute: typeof appAAdminRoute
    }
    '/(app)/a/admin/content': {
      id: '/(app)/a/admin/content'
      path: '/content'
      fullPath: '/a/admin/content'
      preLoaderRoute: typeof appAAdminContentRouteImport
      parentRoute: typeof appAAdminRoute
    }
  }
}

interface appAAdminRouteChildren {
  appAAdminContentRoute: typeof appAAdminContentRoute
  appAAdminDashboardRoute: typeof appAAdminDashboardRoute
  appAAdminLecturersRoute: typeof appAAdminLecturersRoute
  appAAdminSubjectsRoute: typeof appAAdminSubjectsRoute
}

const appAAdminRouteChildren: appAAdminRouteChildren = {
  appAAdminContentRoute: appAAdminContentRoute,
  appAAdminDashboardRoute: appAAdminDashboardRoute,
  appAAdminLecturersRoute: appAAdminLecturersRoute,
  appAAdminSubjectsRoute: appAAdminSubjectsRoute,
}

const appAAdminRouteWithChildren = appAAdminRoute._addFileChildren(
  appAAdminRouteChildren,
)

interface appARouteChildren {
  appAAdminRoute: typeof appAAdminRouteWithChildren
  appAArmeRoute: typeof appAArmeRoute
  appAHomeRoute: typeof appAHomeRoute
  appAProfileRoute: typeof appAProfileRoute
  appASearchRoute: typeof appASearchRoute
  appAForumForumIdRoute: typeof appAForumForumIdRoute
  appAUUserIdRoute: typeof appAUUserIdRoute
  appAUlasanUlasanIdRoute: typeof appAUlasanUlasanIdRoute
  appAForumIndexRoute: typeof appAForumIndexRoute
}

const appARouteChildren: appARouteChildren = {
  appAAdminRoute: appAAdminRouteWithChildren,
  appAArmeRoute: appAArmeRoute,
  appAHomeRoute: appAHomeRoute,
  appAProfileRoute: appAProfileRoute,
  appASearchRoute: appASearchRoute,
  appAForumForumIdRoute: appAForumForumIdRoute,
  appAUUserIdRoute: appAUUserIdRoute,
  appAUlasanUlasanIdRoute: appAUlasanUlasanIdRoute,
  appAForumIndexRoute: appAForumIndexRoute,
}

const appARouteWithChildren = appARoute._addFileChildren(appARouteChildren)

interface ApiChatRouteChildren {
  ApiChatHistoryRoute: typeof ApiChatHistoryRoute
  ApiChatMessagesRoute: typeof ApiChatMessagesRoute
}

const ApiChatRouteChildren: ApiChatRouteChildren = {
  ApiChatHistoryRoute: ApiChatHistoryRoute,
  ApiChatMessagesRoute: ApiChatMessagesRoute,
}

const ApiChatRouteWithChildren =
  ApiChatRoute._addFileChildren(ApiChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appARoute: appARouteWithChildren,
  ApiChatRoute: ApiChatRouteWithChildren,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
