/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as appARouteImport } from './routes/(app)/a'
import { Route as appAHomeRouteImport } from './routes/(app)/a.home'
import { Route as appAForumRouteImport } from './routes/(app)/a.forum'
import { Route as appAArmeRouteImport } from './routes/(app)/a.arme'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const appARoute = appARouteImport.update({
  id: '/(app)/a',
  path: '/a',
  getParentRoute: () => rootRouteImport,
} as any)
const appAHomeRoute = appAHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => appARoute,
} as any)
const appAForumRoute = appAForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => appARoute,
} as any)
const appAArmeRoute = appAArmeRouteImport.update({
  id: '/arme',
  path: '/arme',
  getParentRoute: () => appARoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a': typeof appARouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/a/arme': typeof appAArmeRoute
  '/a/forum': typeof appAForumRoute
  '/a/home': typeof appAHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a': typeof appARouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/a/arme': typeof appAArmeRoute
  '/a/forum': typeof appAForumRoute
  '/a/home': typeof appAHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/a': typeof appARouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/(app)/a/arme': typeof appAArmeRoute
  '/(app)/a/forum': typeof appAForumRoute
  '/(app)/a/home': typeof appAHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/a' | '/auth/callback' | '/a/arme' | '/a/forum' | '/a/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/a' | '/auth/callback' | '/a/arme' | '/a/forum' | '/a/home'
  id:
    | '__root__'
    | '/'
    | '/(app)/a'
    | '/auth/callback'
    | '/(app)/a/arme'
    | '/(app)/a/forum'
    | '/(app)/a/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appARoute: typeof appARouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/a': {
      id: '/(app)/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof appARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/a/home': {
      id: '/(app)/a/home'
      path: '/home'
      fullPath: '/a/home'
      preLoaderRoute: typeof appAHomeRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/forum': {
      id: '/(app)/a/forum'
      path: '/forum'
      fullPath: '/a/forum'
      preLoaderRoute: typeof appAForumRouteImport
      parentRoute: typeof appARoute
    }
    '/(app)/a/arme': {
      id: '/(app)/a/arme'
      path: '/arme'
      fullPath: '/a/arme'
      preLoaderRoute: typeof appAArmeRouteImport
      parentRoute: typeof appARoute
    }
  }
}

interface appARouteChildren {
  appAArmeRoute: typeof appAArmeRoute
  appAForumRoute: typeof appAForumRoute
  appAHomeRoute: typeof appAHomeRoute
}

const appARouteChildren: appARouteChildren = {
  appAArmeRoute: appAArmeRoute,
  appAForumRoute: appAForumRoute,
  appAHomeRoute: appAHomeRoute,
}

const appARouteWithChildren = appARoute._addFileChildren(appARouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appARoute: appARouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
